version: '3.8'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mydbpassword
      MYSQL_DATABASE: wpdatabase
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuserpassword
    volumes:
      - dbdata:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 8080:80
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuserpassword
      WORDPRESS_DB_NAME: wpdatabase
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_INSTALLING', true);
        define('WP_ADMIN_USERNAME', 'admin');
        define('WP_ADMIN_PASSWORD', 'P@ssw0rd');
        define('WP_ADMIN_EMAIL', 'islam.arif87@gmail.com');
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  dbdata:
